USE WAREHOUSE AI_WH;

CREATE DATABASE IF NOT EXISTS SNOWCARE_DEMO;
CREATE SCHEMA IF NOT EXISTS SNOWCARE_DEMO.SUPPORT;
USE SCHEMA SNOWCARE_DEMO.SUPPORT;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PUBLIC;

CREATE OR REPLACE STAGE SUPPORT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR REPLACE TABLE RAW_SUPPORT_TICKETS (
    TICKET_ID                   VARCHAR,
    SUBMIT_DATE                 DATE,
    SUBMIT_TIMESTAMP            TIMESTAMP_NTZ,
    CUSTOMER_ID                 VARCHAR,
    CUSTOMER_TIER               VARCHAR,
    CHANNEL                     VARCHAR,
    PRIORITY                    VARCHAR,
    STATUS                      VARCHAR,
    PRODUCT_AREA                VARCHAR,
    CLASSIFICATION              VARCHAR,
    SENTIMENT                   VARCHAR,
    FIRST_RESPONSE_TIME_HOURS   NUMBER(10,2),
    RESOLUTION_TIME_HOURS       NUMBER(10,2),
    TICKET_SUBJECT              VARCHAR,
    TICKET_DESCRIPTION          TEXT,
    AGENT_NOTES                 TEXT
);

PUT file:///Users/tpetrache/dev/coco_101/data/support_data.csv @SUPPORT_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

COPY INTO RAW_SUPPORT_TICKETS
  FROM @SUPPORT_STAGE/support_data.csv
  FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_UNENCLOSED_FIELD = NONE
  )
  ON_ERROR = 'CONTINUE';
